services:
  client_0:
    build:
      context: ./src/
      dockerfile: client/Dockerfile
    container_name: client_0
    depends_on:
    - usd_filter_0
    - usd_filter_1
    environment:
    - BATCH_SIZE=10
    - INPUT_FILE=/datasets/input_0.csv
    - OUTPUT_FILE=/output/output_0.csv
    - PYTHONUNBUFFERED=1
    - SERVER_HOST=gateway
    - SERVER_PORT=5678
    volumes:
    - ./datasets:/datasets
    - ./output:/output
  client_1:
    build:
      context: ./src/
      dockerfile: client/Dockerfile
    container_name: client_1
    depends_on:
      - usd_filter_0
      - usd_filter_1
    environment:
      - BATCH_SIZE=10
      - INPUT_FILE=/datasets/input_1.csv
      - OUTPUT_FILE=/output/output_1.csv
      - PYTHONUNBUFFERED=1
      - SERVER_HOST=gateway
      - SERVER_PORT=5678
    volumes:
      - ./datasets:/datasets
      - ./output:/output
  date_filter_0:
    build:
      context: ./src/
      dockerfile: date_filter/Dockerfile
    container_name: date_filter_0
    depends_on:
    - sum_0
    - sum_1
    environment:
    - MOM_HOST=rabbitmq
    - MOM_PORT=5672
    - INPUT_QUEUE=date_filter_queue
    - INPUT_EXCHANGE_NAME=usd_exchange
    - INPUT_TOPIC=usd_transactions_topic
    - OUTPUT_EXCHANGE_NAME=date_exchange
    - OUTPUT_TOPIC_1=usd_early_period_transactions_topic
    - OUTPUT_TOPIC_2=usd_later_period_transactions_topic
    - CONTROL_EXCHANGE_NAME=date_filter_control_exchange
    - CONTROL_TOPIC=date_filter_control_topic
    - USD_FILTER_AMOUNT=2
  date_filter_1:
    build:
      context: ./src/
      dockerfile: date_filter/Dockerfile
    container_name: date_filter_1
    depends_on:
    - sum_0
    - sum_1
    environment:
    - MOM_HOST=rabbitmq
    - MOM_PORT=5672
    - INPUT_QUEUE=date_filter_queue
    - INPUT_EXCHANGE_NAME=usd_exchange
    - INPUT_TOPIC=usd_transactions_topic
    - OUTPUT_EXCHANGE_NAME=date_exchange
    - OUTPUT_TOPIC_1=usd_early_period_transactions_topic
    - OUTPUT_TOPIC_2=usd_later_period_transactions_topic
    - CONTROL_EXCHANGE_NAME=date_filter_control_exchange
    - CONTROL_TOPIC=date_filter_control_topic
    - USD_FILTER_AMOUNT=2
  gateway:
    build:
      context: ./src/
      dockerfile: gateway/Dockerfile
    container_name: gateway
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - INPUT_QUEUE=results_queue
    - MOM_HOST=rabbitmq
    - MOM_PORT=5672
    - OUTPUT_EXCHANGE_NAME=transactions_exchange
    - OUTPUT_TOPIC=transactions_topic
    - PYTHONUNBUFFERED=1
    - SERVER_HOST=gateway
    - SERVER_PORT=5678
  rabbitmq:
    build:
      context: ./src/rabbitmq
      dockerfile: Dockerfile
    container_name: rabbitmq
    environment:
    - RABBITMQ_LOG_LEVELS=error
    healthcheck:
      interval: 5s
      retries: 10
      start_period: 50s
      test: rabbitmq-diagnostics check_port_connectivity
      timeout: 3s
    ports:
    - 5672:5672
    - 15672:15672
  sum_0:
    build:
      context: ./src/
      dockerfile: sum/Dockerfile
    container_name: sum_0
    depends_on:
    - promediator_0
    - promediator_1
    environment:
    - MOM_PORT=5672
    - MOM_HOST=rabbitmq
    - INPUT_QUEUE=sum_queue
    - INPUT_TOPIC=usd_early_period_transactions_topic
    - INPUT_EXCHANGE_NAME=date_exchange
    - CONTROL_EXCHANGE_NAME=sum_control_exchange
    - CONTROL_EXCHANGE_TOPIC=sum_control_topic
    - OUTPUT_EXCHANGE_NAME=sum_results_exchange
    - PROMEDIATOR_AMOUNT=2
    - PROMEDIATOR_PREFIX=promediator
    - DATE_FILTER_AMOUNT=2
  sum_1:
    build:
      context: ./src/
      dockerfile: sum/Dockerfile
    container_name: sum_1
    depends_on:
    - promediator_0
    - promediator_1
    environment:
    - MOM_PORT=5672
    - MOM_HOST=rabbitmq
    - INPUT_QUEUE=sum_queue
    - INPUT_TOPIC=usd_early_period_transactions_topic
    - INPUT_EXCHANGE_NAME=date_exchange
    - CONTROL_EXCHANGE_NAME=sum_control_exchange
    - CONTROL_EXCHANGE_TOPIC=sum_control_topic
    - OUTPUT_EXCHANGE_NAME=sum_results_exchange
    - PROMEDIATOR_AMOUNT=2
    - PROMEDIATOR_PREFIX=promediator
    - DATE_FILTER_AMOUNT=2
  usd_filter_0:
    build:
      context: ./src/
      dockerfile: usd_filter/Dockerfile
    container_name: usd_filter_0
    depends_on:
    - date_filter_0
    - date_filter_1
    environment:
    - INPUT_QUEUE=usd_filter_queue
    - INPUT_EXCHANGE_NAME=transactions_exchange
    - INPUT_TOPIC=transactions_topic
    - MOM_HOST=rabbitmq
    - MOM_PORT=5672
    - OUTPUT_EXCHANGE_NAME=usd_exchange
    - OUTPUT_TOPIC=usd_transactions_topic
    - CONTROL_EXCHANGE_NAME=usd_filter_control_exchange
    - CONTROL_TOPIC=usd_filter_control_topic
  usd_filter_1:
    build:
      context: ./src/
      dockerfile: usd_filter/Dockerfile
    container_name: usd_filter_1
    depends_on:
    - date_filter_0
    - date_filter_1
    environment:
    - INPUT_QUEUE=usd_filter_queue
    - INPUT_EXCHANGE_NAME=transactions_exchange
    - INPUT_TOPIC=transactions_topic
    - MOM_HOST=rabbitmq
    - MOM_PORT=5672
    - OUTPUT_EXCHANGE_NAME=usd_exchange
    - OUTPUT_TOPIC=usd_transactions_topic
    - CONTROL_EXCHANGE_NAME=usd_filter_control_exchange
    - CONTROL_TOPIC=usd_filter_control_topic
  promediator_0:
    build:
      context: ./src/
      dockerfile: promediator/Dockerfile
    container_name: promediator_0
    depends_on:
    - transactions_saver_0
    - transactions_saver_1
    environment:
    - ID=0
    - MOM_PORT=5672
    - MOM_HOST=rabbitmq
    - INPUT_EXCHANGE_NAME=sum_results_exchange
    - OUTPUT_EXCHANGE_NAME=promediator_exchange
    - OUTPUT_TOPIC_NAME=promediator_results_topic
    - SUM_AMOUNT=2
    - PROMEDIATOR_PREFIX=promediator
  promediator_1:
    build:
      context: ./src/
      dockerfile: promediator/Dockerfile
    container_name: promediator_1
    depends_on:
    - transactions_saver_0
    - transactions_saver_1
    environment:
    - ID=1
    - MOM_PORT=5672
    - MOM_HOST=rabbitmq
    - INPUT_EXCHANGE_NAME=sum_results_exchange
    - OUTPUT_EXCHANGE_NAME=promediator_exchange
    - OUTPUT_TOPIC_NAME=promediator_results_topic
    - SUM_AMOUNT=2
    - PROMEDIATOR_PREFIX=promediator
  transactions_saver_0:
    build:
      context: ./src/
      dockerfile: transactions_saver/Dockerfile
    container_name: transactions_saver_0
    depends_on:
      - q3_amount_filter_0
      - q3_amount_filter_1
    volumes:
      - ./src/transactions_saver/cache:/storage
    environment:
    - ID=0
    - MOM_PORT=5672
    - MOM_HOST=rabbitmq
    - STORAGE_DIR=/storage
    - INPUT_QUEUE=transactions_saver_queue
    - INPUT_EXCHANGE_NAME=date_exchange
    - INPUT_TOPIC=usd_later_period_transactions_topic
    - OUTPUT_QUEUE=q3_amount_filter_queue
    - NOTIFICATION_EXCHANGE_NAME=notification_exchange
    - NOTIFICATION_TOPIC_NAME=notification_avgs_topic
    - CONTROL_EXCHANGE_NAME=transactions_saver_control_exchange
    - CONTROL_TOPIC_NAME=transactions_saver_control_topic
    - Q3_AMOUNT_FILTER_AMOUNT=2
  transactions_saver_1:
    build:
      context: ./src/
      dockerfile: transactions_saver/Dockerfile
    container_name: transactions_saver_1
    depends_on:
      - q3_amount_filter_0
      - q3_amount_filter_1
    volumes:
      - ./src/transactions_saver/cache:/storage
    environment:
      - ID=1
      - MOM_PORT=5672
      - MOM_HOST=rabbitmq
      - STORAGE_DIR=/storage
      - INPUT_QUEUE=transactions_saver_queue
      - INPUT_EXCHANGE_NAME=date_exchange
      - INPUT_TOPIC=usd_later_period_transactions_topic
      - OUTPUT_QUEUE=q3_amount_filter_queue
      - NOTIFICATION_EXCHANGE_NAME=notification_exchange
      - NOTIFICATION_TOPIC_NAME=notification_avgs_topic
      - CONTROL_EXCHANGE_NAME=transactions_saver_control_exchange
      - CONTROL_TOPIC_NAME=transactions_saver_control_topic
      - Q3_AMOUNT_FILTER_AMOUNT=2
  q3_amount_filter_0:
    build:
      context: ./src/
      dockerfile: q3_amount_filter/Dockerfile
    container_name: q3_amount_filter_0
    depends_on:
      - gateway
    environment:
      - MOM_PORT=5672
      - MOM_HOST=rabbitmq
      - INPUT_PROMEDIATOR_EXCHANGE=promediator_exchange
      - INPUT_PROMEDIATOR_TOPIC=promediator_results_topic
      - INPUT_QUEUE=q3_amount_filter_queue
      - NOTIFICATION_EXCHANGE_NAME=notification_exchange
      - NOTIFICATION_TOPIC_NAME=notification_avgs_topic
      - CONTROL_EXCHANGE_NAME=q3_amount_filter_control_exchange
      - CONTROL_TOPIC_NAME=q3_amount_filter_control_topic
      - OUTPUT_QUEUE=results_queue
      - PROMEDIATOR_AMOUNT=2
      - TRANSACTIONS_SAVER_AMOUNT=2
  q3_amount_filter_1:
    build:
      context: ./src/
      dockerfile: q3_amount_filter/Dockerfile
    container_name: q3_amount_filter_1
    depends_on:
      - gateway
    environment:
      - MOM_PORT=5672
      - MOM_HOST=rabbitmq
      - INPUT_PROMEDIATOR_EXCHANGE=promediator_exchange
      - INPUT_PROMEDIATOR_TOPIC=promediator_results_topic
      - INPUT_QUEUE=q3_amount_filter_queue
      - NOTIFICATION_EXCHANGE_NAME=notification_exchange
      - NOTIFICATION_TOPIC_NAME=notification_avgs_topic
      - CONTROL_EXCHANGE_NAME=q3_amount_filter_control_exchange
      - CONTROL_TOPIC_NAME=q3_amount_filter_control_topic
      - OUTPUT_QUEUE=results_queue
      - PROMEDIATOR_AMOUNT=2
      - TRANSACTIONS_SAVER_AMOUNT=2