services:
  bridge_matcher_0:
    build:
      context: ./src/
      dockerfile: bridge_matcher/Dockerfile
    container_name: bridge_matcher_0
    depends_on:
    - q4_join_0
    environment:
    - MOM_HOST=rabbitmq
    - INPUT_QUEUE=bridge_matcher_queue
    - INPUT_TOPIC=q4_grouped_sus_transactions_topic
    - OUTPUT_TOPIC=bridged_transactions_topic
    - PYTHONUNBUFFERED=1
  client_0:
    build:
      context: ./src/
      dockerfile: client/Dockerfile
    container_name: client_0
    depends_on:
    - usd_filter_0
    environment:
    - BATCH_SIZE = 10
    - INPUT_FILE=/datasets/input_0.csv
    - OUTPUT_FILE=/output/output_0.csv
    - PYTHONUNBUFFERED=1
    - SERVER_HOST=gateway
    - SERVER_PORT=5678
    volumes:
    - ./datasets:/datasets
    - ./output:/output
  date_filter_0:
    build:
      context: ./src/
      dockerfile: date_filter/Dockerfile
    container_name: date_filter_0
    depends_on:
    - group_0
    environment:
    - MOM_HOST=rabbitmq
    - INPUT_QUEUE=date_filter_queue
    - INPUT_TOPIC=usd_transactions_topic
    - OUTPUT_TOPIC_1=usd_early_period_transactions_topic
    - PYTHONUNBUFFERED=1
  gateway:
    build:
      context: ./src/
      dockerfile: gateway/Dockerfile
    container_name: gateway
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - INPUT_TOPIC=results_topic
    - MOM_HOST=rabbitmq
    - OUTPUT_TOPIC=transactions_topic
    - PYTHONUNBUFFERED=1
    - SERVER_HOST=gateway
    - SERVER_PORT=5678
  group_0:
    build:
      context: ./src/
      dockerfile: group/Dockerfile
    container_name: group_0
    depends_on:
    - bridge_matcher_0
    environment:
    - MOM_HOST=rabbitmq
    - INPUT_QUEUE=group_queue
    - INPUT_TOPIC=usd_early_period_transactions_topic
    - OUTPUT_TOPIC=q4_grouped_sus_transactions_topic
    - PYTHONUNBUFFERED=1
  q4_join_0:
    build:
      context: ./src/
      dockerfile: join/Dockerfile
    container_name: q4_join_0
    depends_on:
    - gateway
    environment:
    - MOM_HOST=rabbitmq
    - INPUT_TOPIC=bridged_transactions_topic
    - OUTPUT_TOPIC=results_topic
    - PYTHONUNBUFFERED=1
  rabbitmq:
    build:
      context: ./src/rabbitmq
      dockerfile: Dockerfile
    container_name: rabbitmq
    environment:
    - RABBITMQ_LOG_LEVELS=error
    healthcheck:
      interval: 5s
      retries: 10
      start_period: 50s
      test: rabbitmq-diagnostics check_port_connectivity
      timeout: 3s
    ports:
    - 5672:5672
    - 15672:15672
  usd_filter_0:
    build:
      context: ./src/
      dockerfile: usd_filter/Dockerfile
    container_name: usd_filter_0
    depends_on:
    - date_filter_0
    environment:
    - INPUT_QUEUE=usd_filter_queue
    - INPUT_TOPIC=transactions_topic
    - OUTPUT_TOPIC=usd_transactions_topic
    - MOM_HOST=rabbitmq
    - PYTHONUNBUFFERED=1
