services:
  bridge_matcher_0:
    build:
      context: ./src/
      dockerfile: bridge_matcher/Dockerfile
    container_name: bridge_matcher_0
    depends_on:
    - q4_join_0
    environment:
    - ID=0
    - WORKER_ID=bridge_matcher_0
    - WORKER_PREFIX=bridge_matcher
    - MOM_HOST=rabbitmq
    - MOM_PORT=5672
    - INPUT_EXCHANGE_NAME=bridge_matcher_exchange
    - CONTROL_EXCHANGE_NAME=bridge_matcher_control_exchange
    - OUTPUT_EXCHANGE_NAME=q4_join_exchange
    - WORKERS_AMOUNT=3
    - PREV_FASE_WORKERS_AMOUNT=3
    - NEXT_FASE_WORKERS_AMOUNT=1
    - NEXT_FASE_WORKERS_PREFIX=q4_join
    - PYTHONUNBUFFERED=1
    volumes:
    - ./persistence:/persistence 
  bridge_matcher_1:
    build:
      context: ./src/
      dockerfile: bridge_matcher/Dockerfile
    container_name: bridge_matcher_1
    depends_on:
    - q4_join_0
    environment:
    - ID=1
    - WORKER_ID=bridge_matcher_1
    - WORKER_PREFIX=bridge_matcher
    - MOM_HOST=rabbitmq
    - MOM_PORT=5672
    - INPUT_EXCHANGE_NAME=bridge_matcher_exchange
    - CONTROL_EXCHANGE_NAME=bridge_matcher_control_exchange
    - OUTPUT_EXCHANGE_NAME=q4_join_exchange
    - WORKERS_AMOUNT=3
    - PREV_FASE_WORKERS_AMOUNT=3
    - NEXT_FASE_WORKERS_AMOUNT=1
    - NEXT_FASE_WORKERS_PREFIX=q4_join
    - PYTHONUNBUFFERED=1
    volumes:
    - ./persistence:/persistence 
  bridge_matcher_2:
    build:
      context: ./src/
      dockerfile: bridge_matcher/Dockerfile
    container_name: bridge_matcher_2
    depends_on:
    - q4_join_0
    environment:
    - ID=2
    - WORKER_ID=bridge_matcher_2
    - WORKER_PREFIX=bridge_matcher
    - MOM_HOST=rabbitmq
    - MOM_PORT=5672
    - INPUT_EXCHANGE_NAME=bridge_matcher_exchange
    - CONTROL_EXCHANGE_NAME=bridge_matcher_control_exchange
    - OUTPUT_EXCHANGE_NAME=q4_join_exchange
    - WORKERS_AMOUNT=3
    - PREV_FASE_WORKERS_AMOUNT=3
    - NEXT_FASE_WORKERS_AMOUNT=1
    - NEXT_FASE_WORKERS_PREFIX=q4_join
    - PYTHONUNBUFFERED=1
    volumes:
    - ./persistence:/persistence 
  client_0:
    build:
      context: ./src/
      dockerfile: client/Dockerfile
    container_name: client_0
    depends_on:
    - usd_filter_0
    - usd_filter_1
    environment:
    - ID=0
    - WORKER_ID=client_0
    - BATCH_SIZE=100
    - INPUT_FILE=/datasets/input_0.csv
    - OUTPUT_FILE=/output/output.csv
    - PYTHONUNBUFFERED=1
    - SERVER_HOST=gateway
    - SERVER_PORT=5678
    volumes:
    - ./persistence:/persistence 
    - ./datasets:/datasets
    - ./output:/output
  date_filter_0:
    build:
      context: ./src/
      dockerfile: date_filter/Dockerfile
    container_name: date_filter_0
    depends_on:
    - group_0
    - group_1
    - group_2
    environment:
    - ID=0
    - WORKER_ID=date_filter_0
    - MOM_HOST=rabbitmq
    - MOM_PORT=5672
    - INPUT_QUEUE=date_filter_queue
    - INPUT_EXCHANGE_NAME=usd_exchange
    - INPUT_TOPIC=usd_transactions_topic
    - OUTPUT_EXCHANGE_NAME=date_exchange
    - OUTPUT_TOPIC_1=usd_early_period_transactions_topic
    - OUTPUT_TOPIC_2=usd_later_period_transactions_topic
    - CONTROL_EXCHANGE_NAME=date_filter_control_exchange
    - CONTROL_TOPIC=date_filter_control_topic
    - USD_FILTER_AMOUNT=2
    volumes:
    - ./persistence:/persistence 
  date_filter_1:
    build:
      context: ./src/
      dockerfile: date_filter/Dockerfile
    container_name: date_filter_1
    depends_on:
      - group_0
      - group_1
      - group_2
    environment:
    - ID=1
    - WORKER_ID=date_filter_1
    - MOM_HOST=rabbitmq
    - MOM_PORT=5672
    - INPUT_QUEUE=date_filter_queue
    - INPUT_EXCHANGE_NAME=usd_exchange
    - INPUT_TOPIC=usd_transactions_topic
    - OUTPUT_EXCHANGE_NAME=date_exchange
    - OUTPUT_TOPIC_1=usd_early_period_transactions_topic
    - OUTPUT_TOPIC_2=usd_later_period_transactions_topic
    - CONTROL_EXCHANGE_NAME=date_filter_control_exchange
    - CONTROL_TOPIC=date_filter_control_topic
    - USD_FILTER_AMOUNT=2
    volumes:
    - ./persistence:/persistence 
  gateway:
    build:
      context: ./src/
      dockerfile: gateway/Dockerfile
    container_name: gateway
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - INPUT_QUEUE=results_queue
    - MOM_HOST=rabbitmq
    - MOM_PORT=5672
    - OUTPUT_EXCHANGE_NAME=transactions_exchange
    - OUTPUT_TOPIC=transactions_topic
    - PYTHONUNBUFFERED=1
    - SERVER_HOST=gateway
    - SERVER_PORT=5678
    - EOF_EXPECTED_BY_QUERY_1=0
    - EOF_EXPECTED_BY_QUERY_2=0
    - EOF_EXPECTED_BY_QUERY_3=0
    - EOF_EXPECTED_BY_QUERY_4=1 # Coincidir con la cantidad de q4 join
    - EOF_EXPECTED_BY_QUERY_5=0
  group_0:
    build:
      context: ./src/
      dockerfile: group/Dockerfile
    container_name: group_0
    depends_on:
    - bridge_matcher_0
    - bridge_matcher_1
    environment:
    - ID=0
    - WORKER_ID=group_0
    - WORKER_PREFIX=group
    - MOM_HOST=rabbitmq
    - MOM_PORT=5672
    - INPUT_QUEUE=group_queue
    - INPUT_TOPIC=usd_early_period_transactions_topic
    - INPUT_EXCHANGE_NAME=date_exchange
    - OUTPUT_EXCHANGE_NAME=bridge_matcher_exchange
    - CONTROL_EXCHANGE_NAME=group_control_exchange_name
    - NEXT_FASE_WORKERS_AMOUNT=3
    - NEXT_FASE_WORKERS_PREFIX=bridge_matcher
    - DATE_FILTER_AMOUNT=2
    - PYTHONUNBUFFERED=1
    volumes:
    - ./persistence:/persistence 
  group_1:
    build:
      context: ./src/
      dockerfile: group/Dockerfile
    container_name: group_1
    depends_on:
    - bridge_matcher_0
    - bridge_matcher_1
    environment:
    - ID=1
    - WORKER_ID=group_1
    - WORKER_PREFIX=group
    - MOM_HOST=rabbitmq
    - MOM_PORT=5672
    - INPUT_QUEUE=group_queue
    - INPUT_TOPIC=usd_early_period_transactions_topic
    - INPUT_EXCHANGE_NAME=date_exchange
    - OUTPUT_EXCHANGE_NAME=bridge_matcher_exchange
    - CONTROL_EXCHANGE_NAME=group_control_exchange_name
    - NEXT_FASE_WORKERS_AMOUNT=3
    - NEXT_FASE_WORKERS_PREFIX=bridge_matcher
    - DATE_FILTER_AMOUNT=2
    - PYTHONUNBUFFERED=1
    volumes:
    - ./persistence:/persistence 
  group_2:
    build:
      context: ./src/
      dockerfile: group/Dockerfile
    container_name: group_2
    depends_on:
    - bridge_matcher_0
    - bridge_matcher_1
    environment:
    - ID=2
    - WORKER_ID=group_2
    - WORKER_PREFIX=group
    - MOM_HOST=rabbitmq
    - MOM_PORT=5672
    - INPUT_QUEUE=group_queue
    - INPUT_TOPIC=usd_early_period_transactions_topic
    - INPUT_EXCHANGE_NAME=date_exchange
    - OUTPUT_EXCHANGE_NAME=bridge_matcher_exchange
    - CONTROL_EXCHANGE_NAME=group_control_exchange_name
    - NEXT_FASE_WORKERS_AMOUNT=3
    - NEXT_FASE_WORKERS_PREFIX=bridge_matcher
    - DATE_FILTER_AMOUNT=2
    - PYTHONUNBUFFERED=1
    volumes:
    - ./persistence:/persistence 
  q4_join_0:
    build:
      context: ./src/
      dockerfile: q4_join/Dockerfile
    container_name: q4_join_0
    depends_on:
    - gateway
    environment:
    - ID=0
    - WORKER_ID=q4_join_0
    - WORKER_PREFIX=q4_join
    - MOM_HOST=rabbitmq
    - MOM_PORT=5672
    - INPUT_EXCHANGE_NAME=q4_join_exchange
    - OUTPUT_QUEUE_NAME=results_queue
    - PREV_FASE_WORKERS_AMOUNT=3
    - PYTHONUNBUFFERED=1
    volumes:
    - ./persistence:/persistence 
  rabbitmq:
    build:
      context: ./src/rabbitmq
      dockerfile: Dockerfile
    container_name: rabbitmq
    environment:
    - RABBITMQ_LOG_LEVELS=error
    healthcheck:
      interval: 5s
      retries: 10
      start_period: 50s
      test: rabbitmq-diagnostics check_port_connectivity
      timeout: 3s
    ports:
    - 5672:5672
    - 15672:15672
  usd_filter_0:
    build:
      context: ./src/
      dockerfile: usd_filter/Dockerfile
    container_name: usd_filter_0
    depends_on:
    - date_filter_0
    - date_filter_1
    environment:
    - ID=0
    - WORKER_ID=usd_filter_0
    - INPUT_QUEUE=usd_filter_queue
    - INPUT_EXCHANGE_NAME=transactions_exchange
    - INPUT_TOPIC=transactions_topic
    - MOM_HOST=rabbitmq
    - MOM_PORT=5672
    - OUTPUT_EXCHANGE_NAME=usd_exchange
    - OUTPUT_TOPIC=usd_transactions_topic
    - CONTROL_EXCHANGE_NAME=usd_filter_control_exchange
    - CONTROL_TOPIC=usd_filter_control_topic
  usd_filter_1:
    build:
      context: ./src/
      dockerfile: usd_filter/Dockerfile
    container_name: usd_filter_1
    depends_on:
    - date_filter_1
    - date_filter_0
    environment:
    - ID=1
    - WORKER_ID=usd_filter_0
    - INPUT_QUEUE=usd_filter_queue
    - INPUT_EXCHANGE_NAME=transactions_exchange
    - INPUT_TOPIC=transactions_topic
    - MOM_HOST=rabbitmq
    - MOM_PORT=5672
    - OUTPUT_EXCHANGE_NAME=usd_exchange
    - OUTPUT_TOPIC=usd_transactions_topic
    - CONTROL_EXCHANGE_NAME=usd_filter_control_exchange
    - CONTROL_TOPIC=usd_filter_control_topic