services:
  client_0:
    build:
      context: ./src/
      dockerfile: client/Dockerfile
    container_name: client_0
    depends_on:
    - usd_filter_0
    - usd_filter_1
    environment:
    - ID=0
    - BATCH_SIZE=200
    - INPUT_FILE=/datasets/input_0.csv
    - OUTPUT_FILE=/output/output.csv
    - PYTHONUNBUFFERED=1
    - SERVER_HOST=gateway
    - SERVER_PORT=5678
    #- CRASH_AFTER_LOG=300
    volumes:
    - ./persistence:/persistence 
    - ./datasets:/datasets
    - ./output:/output
  q2_counter_0:
    build:
      context: ./src/
      dockerfile: counter_q2/Dockerfile
    container_name: q2_counter_0
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - ID=0
    - MOM_HOST=rabbitmq
    - MOM_PORT=5672
    - INPUT_QUEUE=counter_q2_queue
    - INPUT_EXCHANGE_NAME=usd_transactions_exchange
    - INPUT_TOPIC=usd_transactions_topic
    - OUTPUT_PREFIX=join_q2
    - JOIN_AMOUNT=2
    - COUNTER_AMOUNT=2
    - COUNTER_Q2_CONTROL=counter_q2_control
    - BATCH_SIZE=100
    - USD_FILTER_AMOUNT=2
    volumes:
    - ./persistence:/persistence 
  q2_counter_1:
    build:
      context: ./src/
      dockerfile: counter_q2/Dockerfile
    container_name: q2_counter_1
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - ID=1
    - MOM_HOST=rabbitmq
    - MOM_PORT=5672
    - INPUT_QUEUE=counter_q2_queue
    - INPUT_EXCHANGE_NAME=usd_transactions_exchange
    - INPUT_TOPIC=usd_transactions_topic
    - OUTPUT_PREFIX=join_q2
    - JOIN_AMOUNT=2
    - COUNTER_AMOUNT=2
    - COUNTER_Q2_CONTROL=counter_q2_control
    - BATCH_SIZE=100
    - USD_FILTER_AMOUNT=2
    volumes:
    - ./persistence:/persistence
  gateway:
    build:
      context: ./src/
      dockerfile: gateway/Dockerfile
    container_name: gateway
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - INPUT_QUEUE=results_queue
    - MOM_HOST=rabbitmq
    - MOM_PORT=5672
    - OUTPUT_EXCHANGE_NAME=transactions_exchange
    - OUTPUT_TOPIC=transactions_topic
    - PYTHONUNBUFFERED=1
    - SERVER_HOST=gateway
    - SERVER_PORT=5678
    - EOF_EXPECTED_BY_QUERY_1=0
    - EOF_EXPECTED_BY_QUERY_2=2 # Coincidir con la cantidad de q2 counters
    - EOF_EXPECTED_BY_QUERY_3=0
    - EOF_EXPECTED_BY_QUERY_4=0
    - EOF_EXPECTED_BY_QUERY_5=0
  q2_join_0:
    build:
      context: ./src/
      dockerfile: join_q2/Dockerfile
    container_name: q2_join_0
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - ID=0
    - MOM_HOST=rabbitmq
    - MOM_PORT=5672
    - INPUT_PREFIX=join_q2
    - COUNTER_AMOUNT=2
    - OUTPUT_QUEUE=results_queue
    - QUERY_ID=5
    - BATCH_SIZE=100
  q2_join_1:
    build:
      context: ./src/
      dockerfile: join_q2/Dockerfile
    container_name: q2_join_1
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - ID=1
    - MOM_HOST=rabbitmq
    - MOM_PORT=5672
    - INPUT_PREFIX=join_q2
    - COUNTER_AMOUNT=2
    - OUTPUT_QUEUE=results_queue
    - QUERY_ID=5
    - BATCH_SIZE=100
  rabbitmq:
    build:
      context: ./src/rabbitmq
      dockerfile: Dockerfile
    container_name: rabbitmq
    environment:
    - RABBITMQ_LOG_LEVELS=error
    healthcheck:
      interval: 5s
      retries: 10
      start_period: 50s
      test: rabbitmq-diagnostics check_port_connectivity
      timeout: 3s
    ports:
    - 5672:5672
    - 15672:15672
  usd_filter_0:
    build:
      context: ./src/
      dockerfile: usd_filter/Dockerfile
    container_name: usd_filter_0
    depends_on:
    - q2_counter_0
    - q2_counter_1
    environment:
    - ID=0
    - INPUT_QUEUE=usd_filter_queue
    - INPUT_EXCHANGE_NAME=transactions_exchange
    - INPUT_TOPIC=transactions_topic
    - MOM_HOST=rabbitmq
    - MOM_PORT=5672
    - OUTPUT_EXCHANGE_NAME=usd_transactions_exchange
    - OUTPUT_TOPIC=usd_transactions_topic
    - CONTROL_EXCHANGE_NAME=usd_filter_control_exchange
    - CONTROL_TOPIC=usd_filter_control_topic
  usd_filter_1:
    build:
      context: ./src/
      dockerfile: usd_filter/Dockerfile
    container_name: usd_filter_1
    depends_on:
    - q2_counter_0
    - q2_counter_1
    environment:
    - ID=1
    - INPUT_QUEUE=usd_filter_queue
    - INPUT_EXCHANGE_NAME=transactions_exchange
    - INPUT_TOPIC=transactions_topic
    - MOM_HOST=rabbitmq
    - MOM_PORT=5672
    - OUTPUT_EXCHANGE_NAME=usd_transactions_exchange
    - OUTPUT_TOPIC=usd_transactions_topic
    - CONTROL_EXCHANGE_NAME=usd_filter_control_exchange
    - CONTROL_TOPIC=usd_filter_control_topic