services:
  q1_amount_filter_0:
    build:
      context: ./src/
      dockerfile: q1_amount_filter/Dockerfile
    container_name: q1_amount_filter_0
    depends_on:
    - gateway
    environment:
    - ID=0
    - MOM_HOST=rabbitmq
    - MOM_PORT=5672
    - INPUT_QUEUE=amount_filter_q1_queue
    - INPUT_EXCHANGE_NAME=usd_exchange
    - INPUT_TOPIC=usd_transactions_topic
    - OUTPUT_QUEUE=results_queue
    - CONTROL_EXCHANGE_NAME=q1_amount_filter_control_exchange
    - CONTROL_TOPIC=q1_amount_filter_control_topic
    - USD_FILTER_AMOUNT=2
  q1_amount_filter_1:
    build:
      context: ./src/
      dockerfile: q1_amount_filter/Dockerfile
    container_name: q1_amount_filter_1
    depends_on:
      - gateway
    environment:
      - ID=1
      - MOM_HOST=rabbitmq
      - MOM_PORT=5672
      - INPUT_QUEUE=amount_filter_q1_queue
      - INPUT_EXCHANGE_NAME=usd_exchange
      - INPUT_TOPIC=usd_transactions_topic
      - OUTPUT_QUEUE=results_queue
      - CONTROL_EXCHANGE_NAME=q1_amount_filter_control_exchange
      - CONTROL_TOPIC=q1_amount_filter_control_topic
      - USD_FILTER_AMOUNT=2
  client_0:
    build:
      context: ./src/
      dockerfile: client/Dockerfile
    container_name: client_0
    depends_on:
    - usd_filter_0
    - usd_filter_1
    environment:
    - ID=0
    - BATCH_SIZE=200
    - INPUT_FILE=/datasets/input_0.csv
    - OUTPUT_FILE=/output/output.csv
    - PYTHONUNBUFFERED=1
    - SERVER_HOST=gateway
    - SERVER_PORT=5678
    #- CRASH_AFTER_SEND_DATA=100
    volumes:
    - ./datasets:/datasets
    - ./output:/output
    - ./persistence:/persistence 
  gateway:
    build:
      context: ./src/
      dockerfile: gateway/Dockerfile
    container_name: gateway
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
    - INPUT_QUEUE=results_queue
    - MOM_HOST=rabbitmq
    - MOM_PORT=5672
    - OUTPUT_EXCHANGE_NAME=transactions_exchange
    - OUTPUT_TOPIC=transactions_topic
    - PYTHONUNBUFFERED=1
    - SERVER_HOST=gateway
    - SERVER_PORT=5678
    - EOF_EXPECTED_BY_QUERY_1=2 # Coincidir con la cantidad de q1 amount filters
    - EOF_EXPECTED_BY_QUERY_2=0
    - EOF_EXPECTED_BY_QUERY_3=0
    - EOF_EXPECTED_BY_QUERY_4=0
    - EOF_EXPECTED_BY_QUERY_5=0
  rabbitmq:
    build:
      context: ./src/rabbitmq
      dockerfile: Dockerfile
    container_name: rabbitmq
    environment:
    - RABBITMQ_LOG_LEVELS=error
    healthcheck:
      interval: 5s
      retries: 10
      start_period: 50s
      test: rabbitmq-diagnostics check_port_connectivity
      timeout: 3s
    ports:
    - 5672:5672
    - 15672:15672
  usd_filter_0:
    build:
      context: ./src/
      dockerfile: usd_filter/Dockerfile
    container_name: usd_filter_0
    depends_on:
    - q1_amount_filter_0
    - q1_amount_filter_1
    environment:
    - ID=0
    - INPUT_QUEUE=usd_filter_queue
    - INPUT_EXCHANGE_NAME=transactions_exchange
    - INPUT_TOPIC=transactions_topic
    - MOM_HOST=rabbitmq
    - MOM_PORT=5672
    - OUTPUT_EXCHANGE_NAME=usd_exchange
    - OUTPUT_TOPIC=usd_transactions_topic
    - CONTROL_EXCHANGE_NAME=usd_filter_control_exchange
    - CONTROL_TOPIC=usd_filter_control_topic
  usd_filter_1:
    build:
      context: ./src/
      dockerfile: usd_filter/Dockerfile
    container_name: usd_filter_1
    depends_on:
      - q1_amount_filter_0
      - q1_amount_filter_1
    environment:
      - ID=1
      - INPUT_QUEUE=usd_filter_queue
      - INPUT_EXCHANGE_NAME=transactions_exchange
      - INPUT_TOPIC=transactions_topic
      - MOM_HOST=rabbitmq
      - MOM_PORT=5672
      - OUTPUT_EXCHANGE_NAME=usd_exchange
      - OUTPUT_TOPIC=usd_transactions_topic
      - CONTROL_EXCHANGE_NAME=usd_filter_control_exchange
      - CONTROL_TOPIC=usd_filter_control_topic